### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by tfalamu** [iohype/clipShare-Desktop#2]
Running on Ubuntu Linux 20.04
- ClipShare Desktop does not start a server at the promised port (9090). 
- Clicking "Stop Hosting" does nothing but freeze the button.

**Comment by o4codes** [comment]
As noticed on most linux installers after the installation, the main server which is pbgopy is not marked as "allow execution as a program" after installation.
![Screenshot from 2021-01-29 12-27-05](https://user-images.githubusercontent.com/38965607/106307443-60ae0600-622d-11eb-96f8-22622a7b1ec1.png)

By navigating to your install directory, the pbgopy server can then marked for execution as as a program.

The next Beta release aims to resolve this issue by embedding a light http server with the Java program itself

**Comment by tfalamu** [comment]
Looking forward to the beta, but is it not possible to get by that bug by using **chmod**? At the terminal, I would allow execution by running ```chmod +x pbgopy```

**Comment by o4codes** [comment]
Internal server created with Javalin hence no need for an external server
